### ISSUE TITLE
XEPs to implement

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-macos#1]
* XEP-001: XMPP Extension Protocols
* XEP-0012: Last Activity
* XEP-0045: Multi-User Chat
* XEP-0055: Jabber Search
* XEP-0080: User Location
* XEP-0084: User Avatar
* XEP-0085: Chat State Notifications
* XEP-0092: Software Version
* XEP-0135: File Sharing
* XEP-0138: Stream Compression
* XEP-0166: Jingle
* XEP-0172: User Nickname
* XEP-0198: Stream Management
* XEP-0201: Best Practices for Message Threads
* XEP-0202: Entity Time
* XEP-0203: Delayed Delivery
* XEP-0232: Software Information
* XEP-0256: Last Activity in Presence
* XEP-0266: Codecs for Jingle Audio
* XEP-0272: Multiparty Jingle (Muji)
* XEP-0278: Jingle Relay Nodes
* XEP-0280: Message Carbons
* XEP-0292: vCard4 Over XMPP
* XEP-0299: Codecs for Jingle Video
* XEP-0308: Last Message Correction
* XEP-0311: MUC Fast Reconnect
* XEP-0313: Message Archive Management
* XEP-0327: Rayo
* XEP-0352: Client State Indication
* XEP-0357: Push Notifications
* XEP-0363: HTTP File Upload
* XEP-0384: OMEMO Encryption
* XEP-0390: Entity Capabilities 2.0
* XEP-0393: Message Styling
* XEP-0397: Instant Stream Resumption
* XEP-0400: Multi-Factor Authentication with TOTP
* XEP-0424: Message Retraction
* XEP-0431: Full Text Search in MAM
* XEP-0445: Pre-Authenticated In-Band Registration
* XEP-0446: File metadata element
* XEP-0452: MUC Mention Notifications
* XEP-0459: XMPP Compliance Suites 2022

**Comment by RemiBardon** [comment]
You probably read it, but [XEP-0459](https://xmpp.org/extensions/xep-0459.html) defines XMPP Compliance Suites for 2022, and more specifically, the [IM Compliance Suite](https://xmpp.org/extensions/xep-0459.html#im). All features in this suite must be implemented to be considered XMPP IM compliant.

**Comment by valeriansaliou** [comment]
Yes, this came after this issue. Adding this one to the list 👍🏻
