### ISSUE TITLE
Login failure with valid credentials

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-app-macos#129]
When I try to log into Prose (`main@490db37`), with valid credentials, I get:

```log
request error: <error type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>
```

@valeriansaliou Do you have an idea what's going on? Is my account in a bad state as I haven't logged in for a while?

**Comment by RemiBardon** [comment]
I am logged into Prose web at the same time, maybe it's important to note.

**Comment by nesium** [comment]
If you activate the `PROSE_CORE_LOG_ENABLED` env var and set the `PROSE_CORE_LOG_LEVEL` env var to `TRACE` you should be able to see the data exchange with the server in the Console.app. Could you share the last few messages before the failure occurs? It also happen when the vCard is loaded. That is meant to fail gracefully, but maybe there's a bug.

**Comment by RemiBardon** [comment]
Yes! It didn't cross my mind
I will try soon and send you the logs 🪵

**Comment by nesium** [comment]
Hey Rémi. Could you try again with the latest changes on master? The core lib now includes your patch and I've fixed a couple of issues that affected the first login.

**Comment by RemiBardon** [comment]
On it

**Comment by RemiBardon** [comment]
Seems fixed, I was able to log in and "introduce myself"
