### ISSUE TITLE
Accept donations? 

### ISSUE THREAD

**Issue by solus-hq** [prose-im/prose-app-macos#137]
Hello!

It's a nicely designed and modern XMPP application which could be vital for our team since we're not willing to keep our chats in Telegram. 

I would like to donate to help this project grow. Hope you add some channel to accept cryptocurrency donations as well.

**Comment by valeriansaliou** [comment]
Hello! We could accept donations yes. Would a GH sponsor do? Thank you so much!

**Comment by solus-hq** [comment]
@valeriansaliou

I'm not sure if the GH program allows contributions in cryptocurrencies. You could simply post your BTC/LTC wallet in Readme.md =)
