### ISSUE TITLE
Explain why there's a gh-pages branch

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-app-macos#28]
Write it somewhere we can find it (i.e. README).

See [Slack](https://prose-im.slack.com/archives/C03G1PS24B1/p1654874946195039)

**Comment by valeriansaliou** [comment]
I think we'll use this issue for the records; the gh-pages branch is used to store screenshot image files for the README on master. It's kind of the old-fashioned way to distribute HTTP assets on GH, but it works. Just didn't want to store those assets in master as they are unrelated to the actual code.

**Comment by valeriansaliou** [comment]
gh-pages branch removed, as the README images have been uploaded to GitHub image upload system.
