### ISSUE TITLE
Messaging: Base messaging

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-macos#46]
* [x] Integrate the messaging Web view from the [prose-core-views](https://github.com/prose-im/prose-core-views)
  * Description: The messaging Web view is ready, include it w/ static data

* [x] Pass store data to the messaging Web view
  * Description: Pass store data from Swift to the JS runtime. We should find a way to spawn a single WebKit background process and re-use the same view again and again when the user switches conversation, by simply updating the VueJS store in the view (this avoids re-parsing the JS everytime).

* [x] Ability to send simple text messages and receive them from the network
  * Description: Send messages w/ the `chat` type over XMPP, and receive `chat` messages back.
  * XEPs:
    * RFC3921: Exchanging Messages — https://xmpp.org/rfcs/rfc3921.html#messaging
    * XEP-0308: Last Message Correction — https://xmpp.org/extensions/xep-0308.html
    * XEP-0085: Chat State Notifications — https://xmpp.org/extensions/xep-0085.html
    * XEP-0280: Message Carbons — https://xmpp.org/extensions/xep-0280.html

* [x] Fetch messaging history from the server using MAM (if the server supports MAM) and populate the store
  * Description: Do this upon opening the conversation for the first time since connection broke.
  * XEPs:
    * XEP-0313: Message Archive Management — https://xmpp.org/extensions/xep-0313.html
    * XEP-0441: Message Archive Management Preferences — https://xmpp.org/extensions/xep-0441.html
  
* [x] Support message reactions
  * Description: The WebView should contain a button (on hover?) to add a reaction. Clicking the button would show a native menu. We'd start with UTF emojis only (no user-customized). Maybe a set of 10-20 something emojis would suffice as a start before with go all in with an emoji picker that has multiple pages and a search bar.
  * XEPs:
    * XEP-0444: Message reactions — https://xmpp.org/extensions/xep-0444.html

**Comment by nesium** [comment]
I haven't done anything about Message Carbons yet. My understanding is that the client can just enable/disable this and the server manages the distribution. But I'll read that XEP once again and add a method for toggling the functionality.

**Comment by valeriansaliou** [comment]
From what I recall from the times I implmented it (my memory might be spotty), it addresses the issue where:

1. You'd have two XMPP clients running at the same time, and you'd actively use one;
2. The other parties you're chatting with are sending messages directly to your JID `user@server.tld/used-client-resource`; which means that the other client you're not using (but which is connected), would not get the messages (it would be available in MAM, but the message history would not appear in realtime if it had the same chat open).

Carbons allow those resource-addressed messages to be forward to other connected apps. _From what I recall._
