### ISSUE TITLE
Messaging: Error handling

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-app-macos#47]
* [x] Account offline error banner
  * Description: Whenever the connection broke or is reconnecting (eg. re-opening laptop, waiting for WiFi, server down), show the offline banner (see Sketch designs, will need to be implemented). Still, we should show the offline reason (especially eg. if the server is down and thus we cannot connect at the TCP level).
  * Sub-tasks:
    * [x] Interface implementation
    * [ ] Logic implementation

* [x] Account error popup
  * Description: Whenever the account cannot be connected-to (eg. invalid password, revoked session token), with a way to recover from this state (eg. try to login again).
  * Sub-tasks:
    * [x] Interface implementation
    * [ ] Logic implementation

**Comment by RemiBardon** [comment]
@valeriansaliou Could you separate the UI from the logic in those checkboxes? I'm going to do the UI just now, but the logic will come later.

**Comment by valeriansaliou** [comment]
Just did it, you have sub-checkboxes now.
