### ISSUE TITLE
Giving away SwiftUI code

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-app-macos#8]
I just pulled the project to check something, and when rebasing my branch against `master`, I realized there are changes I never pushed here. Because of recent modularization (#6), those changes cannot be merged as is. I'm too busy right now, and it'll be too late in June, that's why I'm not making a PR.

@nesium Maybe you want to have a look at them, there is a lot of SwiftUI code you could avoid rewriting.

The full diff can be found here: https://github.com/prose-im/prose-app-macos/compare/79cc1c03446f63a4557dad96c0beae8ffa4be421...RemiBardon:3f95129830a349474bb327364c83ad0f0507d75a

**Comment by nesium** [comment]
Thanks, @RemiBardon. These will surely come in handy!
